# Generated by Django 3.0.8 on 2021-04-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('book_average_rating', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('ISBN', models.BigIntegerField()),
                ('ISBN13', models.BigIntegerField()),
                ('book_language_code', models.CharField(max_length=100)),
                ('num_pages', models.PositiveIntegerField()),
                ('ratings_count', models.PositiveIntegerField()),
                ('text_reviews_count', models.PositiveIntegerField()),
                ('publication_date', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
