# Generated by Django 3.0.8 on 2021-04-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=300)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('feedback_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Feedback')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('submitted', 'submitted'), ('executed', 'executed')], max_length=9)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Customer')),
            ],
        ),
    ]
