# Generated by Django 3.0.8 on 2021-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_customer_feedback_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='book',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rater',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
