# Generated by Django 3.0.8 on 2021-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0003_auto_20210424_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.BigIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('number_of_books', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('keyword', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
