# Generated by Django 3.0.8 on 2021-04-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
