# Generated by Django 3.0.8 on 2021-04-29 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (3, '3'), (5, '5'), (6, '6'), (7, '7'), (10, '10'), (9, '9'), (8, '8')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('finishing', 'finishing')], max_length=54),
        ),
        migrations.CreateModel(
            name='Trusted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_who_receving', models.CharField(max_length=100)),
                ('trusted_score', models.PositiveIntegerField(default=0)),
                ('untrusted_score', models.PositiveIntegerField(default=0)),
                ('person_who_voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
