# Generated by Django 3.0.8 on 2021-04-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210429_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusted',
            name='person_voted',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
